In [4]:
import numpy as np
import pandas as pd
df = pd.DataFrame({'a':[1,1,2,12,34,23,45,34,23,12,2,3,4,1], 
 
                   'b':[1,1,2,10000, 10000, 5000, 5002, 40000, 50000, 8000, 5000,3000,15666,1],
 
                    'c':[1,1,2,50, 43, 34, 40, 25, 25, 45, 32,12,32,1],
                   'd':[1,1,2,'a','b','s','d','a','b','s','a','d','a',1]})
df

a      b   c  d
0    1      1   1  1
1    1      1   1  1
2    2      2   2  2
3   12  10000  50  a
4   34  10000  43  b
5   23   5000  34  s
6   45   5002  40  d
7   34  40000  25  a
8   23  50000  25  b
9   12   8000  45  s
10   2   5000  32  a
11   3   3000  12  d
12   4  15666  32  a
13   1      1   1  1

In [5]:
df.drop_duplicates(subset=['c'],keep='last')

a      b   c  d
2    2      2   2  2
3   12  10000  50  a
4   34  10000  43  b
5   23   5000  34  s
6   45   5002  40  d
8   23  50000  25  b
9   12   8000  45  s
11   3   3000  12  d
12   4  15666  32  a
13   1      1   1  1

In [7]:
import pandas as pd

import numpy as np

In [64]:
np.random.seed(1)
arr1=np.random.rand(4)
arr1

array([4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01])

In [76]:
arr2=np.arange(12).reshape(3,4)

np.random.shuffle(arr1)
arr1

array([4.17022005e-01, 3.02332573e-01, 1.14374817e-04, 7.20324493e-01])

In [8]:
arr3=np.array([1,2,3,4,5,6])
arr4=arr3[1:3]
arr4

array([2, 3])

In [9]:
arr3

array([1, 2, 3, 4, 5, 6])